Repository ThinkTank-Unit/66Days-server, pull requests merged in 2024-02, with the labels that each got.

#2 [build #1] 최초 폴더구조 세팅
  .gitignore
  README.md
  build.gradle
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  gradlew.bat
  settings.gradle
  src/main/java/com/thinktank/_66daysserver/Application.java
  src/main/java/com/thinktank/_66daysserver/domain/admin/controller/AdminController.java
  src/main/java/com/thinktank/_66daysserver/domain/admin/dto/AdminReq.java
  src/main/java/com/thinktank/_66daysserver/domain/admin/dto/AdminRes.java
  src/main/java/com/thinktank/_66daysserver/domain/admin/model/Admin.java
  src/main/java/com/thinktank/_66daysserver/domain/admin/repository/AdminRepository.java
  src/main/java/com/thinktank/_66daysserver/domain/admin/service/AdminService.java
  src/main/java/com/thinktank/_66daysserver/domain/admin/service/AdminServiceImpl.java
  src/main/java/com/thinktank/_66daysserver/domain/habit/controller/HabitController.java
  src/main/java/com/thinktank/_66daysserver/domain/habit/dto/HabitReq.java
  src/main/java/com/thinktank/_66daysserver/domain/habit/dto/HabitRes.java
  src/main/java/com/thinktank/_66daysserver/domain/habit/model/Habit.java
  src/main/java/com/thinktank/_66daysserver/domain/habit/repository/HabitRepository.java
  src/main/java/com/thinktank/_66daysserver/domain/habit/service/HabitService.java
  src/main/java/com/thinktank/_66daysserver/domain/habit/service/HabitServiceImpl.java
  src/main/java/com/thinktank/_66daysserver/domain/users/controller/UsersController.java
  src/main/java/com/thinktank/_66daysserver/domain/users/dto/UsersReq.java
  src/main/java/com/thinktank/_66daysserver/domain/users/dto/UsersRes.java
  src/main/java/com/thinktank/_66daysserver/domain/users/model/Users.java
  src/main/java/com/thinktank/_66daysserver/domain/users/repository/UsersRepository.java
  src/main/java/com/thinktank/_66daysserver/domain/users/service/UsersService.java
  src/main/java/com/thinktank/_66daysserver/domain/users/service/UsersServiceImpl.java
  src/main/java/com/thinktank/_66daysserver/global/config/SecurityConfig.java
  src/main/java/com/thinktank/_66daysserver/global/config/WebConfig.java
  src/main/java/com/thinktank/_66daysserver/global/error/CustomErrorType.java
  src/main/java/com/thinktank/_66daysserver/global/error/GlobalExceptionHandler.java
  src/main/java/com/thinktank/_66daysserver/global/security/JwtTokenProvider.java
  src/main/java/com/thinktank/_66daysserver/global/service/NotificationService.java
  src/main/java/com/thinktank/_66daysserver/global/service/NotificationServiceImpl.java
  src/main/resources/application.properties
  src/test/java/com/thinktank/_66daysserver/ApplicationTests.java
Labels: build

#4 [feat #2] 엔티티 구현
  src/main/java/com/thinktank/_66daysserver/domain/habit/model/Habit.java
  src/main/java/com/thinktank/_66daysserver/domain/habit/model/HabitTracking.java
  src/main/java/com/thinktank/_66daysserver/domain/notification/model/Notification.java
  src/main/java/com/thinktank/_66daysserver/domain/users/model/Users.java
  src/main/java/com/thinktank/_66daysserver/global/entity/BaseTime.java
Labels: feat

#6 [feat #5] 습관 CRUD
  src/main/java/com/thinktank/_66daysserver/domain/habit/controller/HabitController.java
  src/main/java/com/thinktank/_66daysserver/domain/habit/dto/HabitReq.java
  src/main/java/com/thinktank/_66daysserver/domain/habit/dto/HabitRes.java
  src/main/java/com/thinktank/_66daysserver/domain/habit/model/Habit.java
  src/main/java/com/thinktank/_66daysserver/domain/habit/repository/HabitRepository.java
  src/main/java/com/thinktank/_66daysserver/domain/habit/service/HabitService.java
  src/main/java/com/thinktank/_66daysserver/domain/habit/service/HabitServiceImpl.java
Labels: feat

#8 [feat #7] 에러 관리
  src/main/java/com/thinktank/_66daysserver/global/error/CustomErrorType.java
  src/main/java/com/thinktank/_66daysserver/global/error/GlobalExceptionHandler.java
  src/main/java/com/thinktank/_66daysserver/global/error/exception/CommonException.java
  src/main/java/com/thinktank/_66daysserver/global/error/exception/HabitException.java
  src/main/java/com/thinktank/_66daysserver/global/error/exception/UserException.java
  src/main/java/com/thinktank/_66daysserver/global/error/handler/GlobalExceptionHandler.java
  src/main/java/com/thinktank/_66daysserver/global/error/model/ErrorResponse.java
  src/main/java/com/thinktank/_66daysserver/global/error/model/FieldErrorResponse.java
  src/main/java/com/thinktank/_66daysserver/global/error/type/AdminErrorType.java
  src/main/java/com/thinktank/_66daysserver/global/error/type/CommonErrorType.java
  src/main/java/com/thinktank/_66daysserver/global/error/type/HabitErrorType.java
  src/main/java/com/thinktank/_66daysserver/global/error/type/UserErrorType.java
Labels: feat

#11 [feat #10] habit service 에러 적용
  src/main/java/com/thinktank/_66daysserver/domain/habit/service/HabitServiceImpl.java
Labels: feat

#15 [feat#14] DB연동
  src/main/java/com/thinktank/_66daysserver/Application.java
  src/main/java/com/thinktank/_66daysserver/domain/habit/dto/HabitReq.java
  src/main/java/com/thinktank/_66daysserver/domain/habit/dto/HabitRes.java
  src/main/resources/application.properties
Labels: feat

#17 Feat #16 Docker 파일 생성 및 properties 추가
  docker-compose.yml
  src/main/resources/application.properties
Labels: feat

#19 [test #18] habit CRUD test
  src/test/java/com/thinktank/_66daysserver/habit/HabitServiceTest.java
Labels: test

#21 [feat #20] notification 설정
  build.gradle
  src/main/appengine/app.yml
  src/main/java/com/thinktank/_66daysserver/domain/notification/controller/NotificationController.java
  src/main/java/com/thinktank/_66daysserver/domain/notification/dto/NotificationReq.java
  src/main/java/com/thinktank/_66daysserver/domain/notification/dto/NotificationRes.java
  src/main/java/com/thinktank/_66daysserver/domain/notification/model/Notification.java
  src/main/java/com/thinktank/_66daysserver/domain/notification/model/NotificationStatus.java
  src/main/java/com/thinktank/_66daysserver/domain/notification/model/NotificationStyle.java
  src/main/java/com/thinktank/_66daysserver/domain/notification/repository/NotificationRepository.java
  src/main/java/com/thinktank/_66daysserver/domain/notification/service/NotificationService.java
  src/main/java/com/thinktank/_66daysserver/domain/notification/service/NotificationServiceImpl.java
  src/main/java/com/thinktank/_66daysserver/domain/users/repository/UsersRepository.java
  src/main/java/com/thinktank/_66daysserver/global/error/exception/NotificationException.java
  src/main/java/com/thinktank/_66daysserver/global/error/type/NotificationErrorType.java
  src/test/java/com/thinktank/_66daysserver/notification/NotificationServiceTest.java
Labels: feat
